# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    name: Publishing to npm.pkg.github.com
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: https://npm.pkg.github.com
        persist-credentials: false

    - run: cd src/node && npm ci
    - run: cd src/node && make build
      env:
        NODE_ENV: production
    - run: npm publish src/node/build/
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
